# Generated by Django 6.1 on 2026-08-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit_property',
            fields=[
                ('unit_id', models.CharField(default='U-0000', primary_key=True, serialize=False)),
                ('property_name', models.CharField(max_length=100)),
                ('property_units', models.CharField(max_length=50, unique=True)),
                ('tenant', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Vacant', 'Vacant'), ('Occupied', 'Occupied'), ('Maintanance', 'Maintanance')], default='Vacant')),
                ('rent_amount', models.PositiveIntegerField(max_length='500')),
                ('lease_start', models.DateField()),
                ('lease_end', models.DateField()),
            ],
        ),
    ]
