# Generated by Django 6.1 on 2026-08-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit_property',
            name='rent_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='unit_property',
            name='status',
            field=models.CharField(choices=[('Occupied', 'Occupied'), ('Maintanance', 'Maintanance'), ('Vacant', 'Vacant')], default='Vacant'),
        ),
    ]
