# Generated by Django 6.1 on 2026-08-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0002_alter_unit_property_rent_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit_property',
            name='property_units',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='unit_property',
            name='status',
            field=models.CharField(choices=[('Maintanance', 'Maintanance'), ('Occupied', 'Occupied'), ('Vacant', 'Vacant')], default='Vacant'),
        ),
    ]
