# Generated by Django 6.1 on 2026-08-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0003_alter_unit_property_property_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit_property',
            name='status',
            field=models.CharField(choices=[('Vacant', 'Vacant'), ('Maintanance', 'Maintanance'), ('Occupied', 'Occupied')], default='Vacant'),
        ),
    ]
