# Generated by Django 6.1 on 2026-08-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0005_alter_unit_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit_property',
            name='status',
            field=models.CharField(choices=[('Maintanance', 'Maintanance'), ('Vacant', 'Vacant'), ('Occupied', 'Occupied')], default='Vacant'),
        ),
    ]
