# Generated by Django 6.1 on 2026-08-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0006_alter_unit_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit_property',
            name='status',
            field=models.CharField(choices=[('Occupied', 'Occupied'), ('Maintanance', 'Maintanance'), ('Vacant', 'Vacant')], default='Vacant'),
        ),
    ]
