# Generated by Django 6.1 on 2026-08-26 07:25

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0008_alter_unit_property_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100)),
                ('landlord_name', models.CharField(max_length=50, verbose_name=django.contrib.auth.models.User)),
            ],
        ),
        migrations.AlterField(
            model_name='unit_property',
            name='status',
            field=models.CharField(choices=[('Occupied', 'Occupied'), ('Maintanance', 'Maintanance'), ('Vacant', 'Vacant')], default='Vacant'),
        ),
    ]
