# Generated by Django 6.1 on 2026-08-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0009_property_alter_unit_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='landlord_name',
            field=models.CharField(max_length=50, verbose_name='Landlord name'),
        ),
        migrations.AlterField(
            model_name='unit_property',
            name='status',
            field=models.CharField(choices=[('Occupied', 'Occupied'), ('Vacant', 'Vacant'), ('Maintanance', 'Maintanance')], default='Vacant'),
        ),
    ]
