# Generated by Django 6.1 on 2026-08-31 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0010_alter_property_landlord_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit_property',
            name='status',
            field=models.CharField(choices=[('Vacant', 'Vacant'), ('Occupied', 'Occupied'), ('Maintanance', 'Maintanance')], default='Vacant'),
        ),
        migrations.CreateModel(
            name='LandlordProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landlord_phone', models.CharField(blank=True, max_length=15)),
                ('landlord_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landlord', to=settings.AUTH_USER_MODEL)),
                ('property_owned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='landlords.property')),
            ],
        ),
    ]
