# Generated by Django 6.1 on 2026-08-17 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landlords', '0004_alter_unit_property_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintanance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_units', models.CharField(max_length=50)),
                ('Maintanance_issue', models.CharField(max_length=500)),
                ('Maintanance_priority', models.CharField(choices=[('Medium', 'Medium'), ('Low', 'Low'), ('Urgent', 'Urgent')])),
                ('created_at', models.DurationField()),
                ('assignment_status', models.CharField(default='Unassigned', max_length=100)),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landlords.unit_property')),
            ],
        ),
    ]
